sudo: required

services:
    - docker

before_install:
    - docker build -t tejozarkar/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true tejozarkar/react-test npm test -- --coverage

after_success:
    - docker build -t tejozarkar/multi-nginx ./nginx
    - docker build -t tejozarkar/multi-server ./server
    - docker build -t tejozarkar/multi-worker ./worker
    - docker build -t tejozarkar/multi-client ./client

    # Login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #Push images to docker hub
    - docker push tejozarkar/multi-nginx
    - docker push tejozarkar/multi-server
    - docker push tejozarkar/multi-worker
    - docker push tejozarkar/multi-client

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: docker-complex
    env: DockerComplex-env
    bucket_name: elasticbeanstalk-us-east-2-509006680370
    bucket_path: docker-complex
    edge: true
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
